config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('post.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import *

app_name = 'post'

urlpatterns = [
    path('liked/<int:post_id>/', PostLiked.as_view(), name='liked'),
    path('saved/<int:post_id>/', PostSaved.as_view(), name='saved'),
    path('create/', PostCreate.as_view(), name='create'),
    path('update/<int:pk>/', PostUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', PostDelete.as_view(), name='delete'),
    path('detail/<int:pk>/', PostDetail.as_view(), name='detail'),
    path('like/', PostLikedList.as_view(), name='liked_list'),
    path('save/', PostSavedList.as_view(), name='saved_list'),
    path('', PostList.as_view(), name='index'),
]

post/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='photos')
    image = models.ImageField(upload_to='timeline_photo/%Y/%m/%d')
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    liked = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='liked', blank=True)
    saved = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='saved', blank=FutureWarning)

    class Meta:
        ordering = ['-created_at']

    def get_absolute_url(self):
        return reverse('post:detail', args=[str(self.id)])

post/views.py
from urllib.parse import urlparse

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView, View

from .models import Post

# 뷰 실행전에 로그인여부, csrf 체크
class PostList(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'post/post_list.html'

class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['image', 'text']
    template_name = 'post/post_create.html'
    success_url = '/'

    def form_valid(self, form):
        # 입력된 항목이 올바른지 체
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            form.instance.save()
            return redirect('/')
        else:
            return self.render_to_response({
                'form': form
            })

class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['image', 'text']
    template_name = 'post/post_update.html'

    # method에 따라 GET/POST 분기
    def dispatch(self, request, *arg, **kwargs):
        object = self.get_object()
        if object.author != request.user:
            messages.warning(request, "수정할 권한이 없습니다")
            return HttpResponseRedirect(object.get_absolute_url())

        return super(PostUpdate, self).dispatch(request, *arg, **kwargs)

class PostDetail(LoginRequiredMixin, DetailView):
    model = Post
    templat_name = 'post/post_detail.html'

class PostDelete(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'post/post_delete.html'
    success_url = '/'

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if object.author != request.user:
            messages.warning(requst, "삭제할 권한이 없습니다.")
            return HttpResponseRedirect(object.get_absolute_url())
        else:
            return super(PostDelete, self).dispatch(request, *args, **kwargs)



class PostLikedList(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'post/post_list.html'

    def get_queryset(self):
        # 로그인한 유저가 좋아요를 클릭한 글을 찾아서 반환
        user = self.request.user
        queryset = user.liked_post.all()
        return queryset

class PostSavedList(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'post/post_list.html'

    def get_queryset(self):
        # 로그인한 유저가 저장한 글을 찾아서 반환
        user = self.request.user
        queryset = user.saved_post.all()
        return queryset

class PostLiked(View):
    def get(self, request, *args, **kwargs):
        # liked를 할 정보가 있다면 진행, 없다면 중
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        else:
            # 1. 어떤 포스팅?
            # url : www.naver.com/blog/like/?photo_id=1
            # request.GET.get('photo_id')
            # url : www.naver.com/blog/like/1/
            # path('blog/like/<int:photo_id>/')
            # kwargs['photo_id']
            # 2. 누가?
            if 'post_id' in kwargs:
                post_id = kwargs['post_id']
                post = Post.objects.get(pk=post_id)
                user = request.user
                if user in post.liked.all():
                    post.liked.remove(user)
                else:
                    post.liked.add(user)

            # 레퍼러 얻기
            referer_url = request.META.get('HTTP_REFERER')
            # https://www.naver.com
            # /blog/doc/1234/
            # ?id=2223
            # domain, path, query
            # path
            path = urlparse(referer_url).path
            return HttpResponseRedirect(path)

class PostSaved(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        else:
            if 'post_id' in kwargs:
                post_id = kwargs['post_id']
                post = Post.objects.get(pk=post_id)
                user = request.user
                if user in post.saved.all():
                    post.liked.remove(user)
                else:
                    post.saved.add(user)
            return HttpResponseRedirect('/')

# signal
# 동작을 하기 전이나 후에 신호를 보냄
# 오버라이드도 할 수 있지만 signal은 한번에 처리하게 할 수 있다
# 1. 어떤 시그널이 발생했을 때 반응할 것이냐?
# 2. 그 시그널이 발생 했을 때 어떻게 알것인가?
@receiver(post_delete, sender=Post)
def post_delete(sender, instance, **kwargs):
    storage = instance.image.storage
    if storage.exists(str(instance.image)):
        storage.delete(str(instance.image))

post/templates/post/layout.html
{%  extends 'templates/layout.html' %}

{% block title %}
{% endblock %}

{% block content %}
{% endblock %}

post/templates/post/post_create.html
{% extends 'layout.html' %}
{% block title %}
Post Create
{% endblock %}

{% block content %}
    <li>
<div class="row">
    <div class="col"></div>
    <div class="col-6">
        <form action="" method="post" enctype="multipart/form-data">
            <div class="alert alert-info">Please enter your Post information.</div>
                {% csrf_token %}
                {{form.as_p}}
            <input type="submit" value="Upload" class="btn btn-outline-primary">
        </form>
    </div>
    <div class="col"></div>
</div>
    </li>
{% endblock %}

post/templates/post/post_delete.html
{% extends 'layout.html' %}
{% block title %}
Post Delete
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-6">
        <form action="" method="post">
            <div class="alert alert-danger">Do you want to delete {{object}}?</div>
                {% csrf_token %}
            <input type="submit" value="Upload" class="btn btn-outline-danger">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

post/templates/post/post_detail.html
{% extends 'layout.html' %}

{% block title %}
    Post Detail
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-6">
        <div class="card" style="margin-top:2em;">
            <div class="card-header">
                {{object.author.username}}
            </div>
            <img src="{{object.image.url}}" class="card-img-top">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <a href="{% url 'post:liked' object.id %}" class="float-left btn-like {%if user in object.liked.all%}active{%endif%}">Liked</a>
                    {% if object.liked.all.count %}

                    <span class="float-left badge badge-danger" style="margin-left:0.5em;">
                        {{object.liked.all.count}}
                    </span>

                    {% endif %}

                    <a href="{% url 'post:saved' object.id %}"  class="float-right btn-save {%if user in object.saved.all%}active{%endif%}">Saved</a>
                </li>
                <li class="list-group-item">
                    <a href="{% url 'post:update' object.id %}" class="card-link">수정</a>
                    <!--//
                    <form action="{% url 'post:delete' object.id %}" method="post">
                        {% csrf_token %}
                        <input type="submit" value="Post Delete" class="btn btn-danger">
                    </form>
                    //-->
                    <a href="{% url 'post:delete' object.id %}" class="card-link">삭제</a>
                </li>
            </ul>

            {% if object.text %}
            <div class="card-body">
                <p class="card-text">{{object.text}}</p>
            </div>
            {% endif %}

            {# load xxx 해당 태그 기능을 지금부터 사용하겠다. #}
            {% load disqus_tags %}
            <div class="card-body">
                {% disqus_show_comments %}
            </div>
        </div>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

post/templates/post/post_list.html
{% extends 'layout.html' %}
{% block title %}
    Post List
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-11 col-lg-7">
        {% for object in object_list %}
        <div class="card" style="margin-top:2em;">
            <div class="card-header">
                {{object.author.username}}
            </div>
            <img src="{{object.image.url}}" class="card-img-top">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <a href="{% url 'post:liked' object.id %}" class="float-left btn-like {%if user in object.liked.all%}active{%endif%}">Liked</a>

                    {% if object.liked.all.count %}
                    <span class="float-left badge badge-danger" style="margin-left:0.5em;">
                        {{object.liked.all.count}}
                    </span>likes

                    {% endif %}

                    <a href="{% url 'post:saved' object.id %}"  class="float-right btn-save {%if user in object.saved.all%}active{%endif%}">Saved</a>
                </li>
            </ul>
            {% if object.text %}
            <div class="card-body">
                <p class="card-text">{{object.text}}</p>
            </div>
            {% endif %}
            <div class="card-body">
                <a href="{{object.get_absolute_url}}" class="card-link">Add a comment...</a>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="col"></div>
</div>
{% endblock %}>

post/templates/post/post_update.html
{% extends 'layout.html' %}

{% block title %}
Post Update
{% endblock %}

{% block content %}
    <li>
<div class="row">
    <div class="col"></div>
    <div class="col-6">
        <form action="" method="post" enctype="multipart/form-data">
            <div class="alert alert-success">Please enter your post information.</div>
                {% csrf_token %}
                {{form.as_p}}
            <input type="submit" value="Update" class="btn btn-outline-primary">
        </form>
    </div>
    <div class="col"></div>
</div>
    </li>
{% endblock %}