accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import UserList, signup

app_name = 'accounts'

urlpatterns = [
    path('user/list/', UserList.as_view(), name='user_list'),
    path('signin/', LoginView.as_view(template_name='accounts/signin.html'), name='signin'),
    path('signout/', LogoutView.as_view(template_name='accounts/signout.html'), name='signout'),
    # 함수형뷰는 이름만 씀
    path('signup/', signup, name='signup'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('post.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import *

app_name = 'post'

urlpatterns = [
    path('liked/<int:post_id>/', PostLiked.as_view(), name='liked'),
    path('saved/<int:post_id>/', PostSaved.as_view(), name='saved'),
    path('create/', PostCreate.as_view(), name='create'),
    path('update/<int:pk>/', PostUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', PostDelete.as_view(), name='delete'),
    path('detail/<int:pk>/', PostDetail.as_view(), name='detail'),
    path('like/', PostLikedList.as_view(), name='liked_list'),
    path('save/', PostSavedList.as_view(), name='saved_list'),
    path('', PostList.as_view(), name='index'),
]

config/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'post:index' %}">Polarogram</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'post:index' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Tags</a>
      </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'post:create' %}">Upload</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:signout' %}">Sign-out</a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:signin' %}">Sign-in</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:signup' %}">Sign-up</a>
        </li>
        {% endif %}
    </ul>
  </div>
</nav>
{% load static %}
<style>
    .btn-like {
        display:inline-block; /* html 요소의 영역 표시 속성 */
        width:24px; /* 너비 */
        height:24px; /* 높이 */
        background:url({% static 'images/button_image.png' %}); /* 배경 이미지 */
        background-position:-231px -131px; /* 배경 이미지 포지션 */
        text-indent:-9999px; /* 영역 안에 있는 텍스트의 들여쓰기 */
        overflow:hidden; /* 영역 바깥으로 밀려난 컨텐츠의 표시여부 */
        border:none; /* 테투리 여부 */
    }
    /*
        어떤 요소를 클릭했을 때, class를 더하거나 빼서 효과를 변경한다.
    */
    .btn-like.active {
        background-position:-231px -105px; /* 배경 이미지 포지션 */
    }

    .btn-save {
        display:inline-block;
        /*
          inline : text형태 컨텐츠가 있는만큼 영역을 차지 하는 형태, 한줄에 여러 요소가 있을 수 있다.
          block : 한줄을 단독으로 차지하고, 크기는 지정할 수 있다.
          inline-block : text형태로 한줄에 여러 요소가 함께 있을 수 있지만, 크기도 지정할 수 있다.
        */
        width:19px;
        height:24px;
        background:url({% static 'images/button_image.png' %});
        background-position:-211px -255px;
        text-indent:-9999px;
        overflow:hidden;
        border:none;
    }

    .btn-save.active {
        background-position:-159px -255px;
    }

</style>
<div id="test_button">

</div>

<div class="container">
    {% if messages %}
    <div class="row">
        <div class="col"></div>
        <div class="col-6">
            {% for message in messages %}
            <div class="alert alert-{{message.tags}}">{{message}}</div>
            {% endfor %}
        </div>
        <div class="col"></div>
    </div>
    {% endif %}
{% block content %}

{% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script type="text/javascript">
    $(function() {
        $('.btn-like').click(function(e) {
            //e.preventDefault();
            //$(this).toggleClass('active');
            //$(this).blur();
        });

        $('.btn-save').click(function(e) {
            //e.preventDefault();
            //$(this).toggleClass('active');
            //$(this).blur();
        });
    });
</script>
</body>
</html>